### ISSUE TITLE
where is the region update code?

### ISSUE THREAD

**Issue by xxAna** [HonglinChu/SiamRPN#1]
Thank you for your sharing! And I wonder if you realize region update part in DaSiam?That is enlarge the search region when the score is low. Thank you  again and waiting for your reply.

**Comment by xiaogeaihighying** [comment]
Sorry,I do not read the code carefully and not do realize region update part in DaSiamRPN


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xxAna"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月10日(星期五) 下午2:49
收件人:&nbsp;"xiaogeaihighying/SiamRPN"<SiamRPN@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xiaogeaihighying/SiamRPN] where is the region update code? (#1)





 
Thank you for your sharing! And I wonder if you realize region update part in DaSiam?That is enlarge the search region when the score is low. Thank you  again and waiting for your reply.

**Comment by xxAna** [comment]
That's OK.Thank you for your reply.
