### ISSUE TITLE
how can i get pretrained model ? we can not get through outside network？

### ISSUE THREAD

**Issue by yanye-hub** [HonglinChu/SiamRPN#3]

**Comment by HonglinChu** [comment]
You can download it from BaiduYun .

https://pan.baidu.com/s/1uPmigK3-O9gPWeWAis_D4g     password:  fanm

**Comment by HonglinChu** [comment]
You can download it from BaiduYun.

https://pan.baidu.com/s/1tENmHYBzomQE31DO5PCmcQ     password:    myw6

**Comment by yanye-hub** [comment]
thank you for you help~
